// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateFile(arg1:string):Promise<void>;

export function CreateFolder(arg1:string):Promise<void>;

export function DeleteFile(arg1:string):Promise<void>;

export function FileExists(arg1:string):Promise<boolean>;

export function GetCurrentProject():Promise<string>;

export function GetRecentFiles():Promise<Array<string>>;

export function Greet(arg1:string):Promise<string>;

export function ListFiles(arg1:string):Promise<Array<main.FileInfo>>;

export function OpenDirectoryDialog():Promise<string>;

export function OpenFileDialog():Promise<string>;

export function ReadFile(arg1:string):Promise<string>;

export function SaveFileDialog(arg1:string):Promise<string>;

export function SetCurrentProject(arg1:string):Promise<void>;

export function SetFullscreen(arg1:boolean):Promise<void>;

export function ToggleFullscreen():Promise<void>;

export function ToggleMaximize():Promise<void>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
